version: '3.9'
services:
  bot_db:
    container_name: bot_db
    image: postgres:14.6-alpine
    environment:
      POSTGRES_DB: bot_db
      POSTGRES_USER: not_a_bot
      POSTGRES_PASSWORD: automata
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - bot_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  bot_api:
    container_name: bot_api

    # image: ignazigelherz/bot_api:latest
    build:
      dockerfile: Dockerfile
      context: ../backend
    restart: always
    environment:
        DB_HOST: bot_db
        DB_NAME: bot_db
        DB_USER: not_a_bot
        DB_PASS: automata

    volumes: 
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    depends_on:
      - bot_db
    env_file:
      - ./.env

  bot_corpus:
    container_name: bot_body
    build:
      context: ../bot
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - bot_api
    env_file:
      - ./.env

  nginx:
    container_name: bot_nginx
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      # - ../docs/:/usr/share/nginx/html/api/docs/

      - static_value:/etc/nginx/html/backend_static/
      - media_value:/etc/nginx/html/backend_media/
    depends_on:
      - bot_api

volumes:
  static_value:
  media_value:
  bot_data:
