# Generated by Django 4.2.2 on 2023-06-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabularFacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VocabularHints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VocabularJokes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polite_joke",
                    models.CharField(unique=True, verbose_name="вежливая шутка"),
                ),
                (
                    "stupid_joke",
                    models.CharField(unique=True, verbose_name="тупая шутка"),
                ),
                ("sarcasm", models.CharField(unique=True, verbose_name="сарказм")),
            ],
            options={
                "verbose_name": "Набор шуток",
                "verbose_name_plural": "Шутки",
            },
        ),
        migrations.CreateModel(
            name="VocabularReactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mistake_light",
                    models.CharField(unique=True, verbose_name="небольшая ошибка"),
                ),
                ("mistake_hard", models.CharField(unique=True, verbose_name="ошибка")),
                (
                    "mistake_critical",
                    models.CharField(unique=True, verbose_name="грубая ошибка"),
                ),
                ("reaction", models.CharField(unique=True, verbose_name="реакция")),
            ],
            options={
                "verbose_name": "Набор реакций",
                "verbose_name_plural": "Реакции",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Задание", "verbose_name_plural": "Задания"},
        ),
        migrations.AddField(
            model_name="task",
            name="task_index",
            field=models.CharField(default=0, verbose_name="индекс"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="answer",
            field=models.IntegerField(verbose_name="правильный ответ"),
        ),
        migrations.AlterField(
            model_name="task",
            name="question",
            field=models.TextField(verbose_name="вопрос"),
        ),
    ]
